# Generated by Django 2.2.6 on 2019-10-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_timeduration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
