# Generated by Django 2.2.6 on 2019-10-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191030_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_timeduration',
        ),
    ]
