# Generated by Django 2.2.6 on 2019-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critique_author', models.CharField(max_length=40, verbose_name='author')),
                ('critique_text', models.TextField(max_length=10000, verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=40, verbose_name='title')),
                ('movie_release_date', models.DateField(blank=True, null=True)),
                ('movie_genre', models.CharField(max_length=20, verbose_name='genre')),
                ('movie_timeduration', models.DateField(blank=True, null=True)),
                ('movie_plot', models.TextField(max_length=5000, verbose_name='plot')),
            ],
        ),
    ]
